### ISSUE TITLE
Changing Admin Dashboard Gui

### ISSUE THREAD

**Issue by zaferhuzmeli** [kubesphere/console#1457]
Hi,
I would like to change my own kubesphere admin dashboard gui like icons, images etc. How to add my changes on my kubesphere admin-panel? I am stopped up on add section just I have docker image in my computer. Could you help me ?

**Comment by calvinyv** [comment]
Legally, KubeSphere doesn't provide this utility because of the protection of copyright, also one of the most valuable resources of this project is the branding of KubeSphere.
The code of the console is opened to everyone, you could customize it as you wish, but make sure you follow the AGPL license.
And the commercial version of KubeSphere is allowed to customize the logo and other elements on GUI, pls contact kubesphere@yunify.com if you have willing to talk about it.
